version: '3'
services:
  db: 
    image: postgres
    restart: always
    volumes:
      - ../../tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pswhere
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      - "3001:1234"
    depends_on:
     - db 
