arangodb:
  operators:
    - "kube-arangodb"
  dependencies:
    java:
      - groupId: "com.arangodb"
        artifactId: "arangodb-java-driver"
    nodejs:
      - "arangojs"
    python:
      - "pyArango"
cassandradb:
  operators:
    - "cassandra-operator"
  dependencies:
    java:
      - groupId: "com.mulesoft.connectors"
        artifactId: "mule-cassandradb-connector"
      - groupId: "org.apache.cassandra"
        artifactId: "cassandra"
    quarkus:
      - configuration: "quarkus.cassandra"
    vertx:
      - groupId: "io.vertx"
        artifactId: "vertx-cassandra-client"
    nodejs:
      - "cassandra-driver"
    python:
      - "cassandra"
clickhouse:
  operators:
    - "clickhouse"
  dependencies:
    java:
      - groupId: "ru.yandex.clickhouse"
        artifactId: "clickhouse-jdbc"
    nodejs:
      - "clickhouse"
    python:
      - "clickhouse"
druid:
  operators:
    - "druid-operator"
  dependencies:
    java:
      - groupId: "in.zapr.druid"
        artifactId: "druidry"
    nodejs:
      - "plywood"
      - "druid-query"
    python:
      - "pydruid"
elasticsearch:
  operators:
    - "elastic-cloud-eck"
    - "esindex-operator"
    - "elastic-phenix-operator"
  dependencies:
    java:
      - groupId: "org.elasticsearch.client"
        artifactId: "elasticsearch-rest-high-level-client"
    quarkus:
      - groupId: "io.quarkus"
        artifactId: "quarkus-elasticsearch-rest-client"
    nodejs:
      - "@elastic/elasticsearch"
    python:
      - "elasticsearch"
etcd:
  operators:
    - "etcd"
  dependencies:
    java:
      - groupId: "io.etcd"
        artifactId: "jetcd-core"
    nodejs:
      - "etcd3"
    python:
      - "etcd"
kafka:
  operators:
    - "banzaicloud-kafka-operator"
    - "strimzi-kafka-operator"
  dependencies:
    java:
      - groupId: "org.apache.kafka"
        artifactId: "kafka-clients"
    quarkus:
      - groupId: "io.quarkus"
        artifactId: "quarkus-smallrye-reactive-messaging-kafka"
        configuration: "kafka.bootstrap.servers"
    vertx:
      - groupId: "io.vertx"
        artifactId: "vertx-kafka-client"
    nodejs:
      - "kafkajs"
      - "rdkafka"
    python:
      - "kafka"
mariadb:
  operators:
    - "mariadb-operator-app"
  dependencies:
    java:
      - groupId: "org.mariadb.jdbc"
        artifactId: "mariadb-java-client"
    quarkus:
      - configuration: "db-kind=mariadb"
    nodejs:
      - "mariadb"
    python:
      - "mariadb"
mongodb:
  operators:
    - "mongodb-atlas-kubernetes"
    - "mongodb-enterprise"
    - "percona-server-mongodb-operator"
  dependencies:
    java:
      - groupId: "org.mongodb"
        artifactId: "mongo-java"
    quarkus:
      - groupId: "io.quarkus"
        artifactId: "quarkus-mongodb"
        configuration: "quarkus.mongodb"
    vertx:
      - groupId: "io.vertx"
        artifactId: "vertx-mongo-client"
    nodejs:
      - "mongodb"
      - "mongoose"
    python:
      - "pymongo"
mysql:
  operators:
    - "mysql"
    - "percona-xtradb-cluster-operator"
    - "planetscale"
  dependencies:
    java:
      - groupId: "mysql"
        artifactId: "mysql-connector-java"
    quarkus:
      - groupId: "io.quarkus"
        artifactId: "quarkus-reactive-mysql-client"
        configuration: ".db-kind=mysql"
    vertx:
      - groupId: "io.vertx"
        artifactId: "vertx-mysql-client"
    nodejs:
      - "mysql"
      - "mysql2"
    python:
      - "mysql.connector"
      - "mysql"
postgresql:
  operators:
    - "cloud-native-postgresql"
    - "postgresql"
    - "postgres-operator"
    - "postgresql-operator-dev4devs-com"
  dependencies:
    java:
      - groupId: "org.postgresql"
        artifactId: "postgresql"
    quarkus:
      - groupId: "io.quarkus"
        artifactId: "quarkus-reactive-pg-client"
        configuration: ".db-kind=postgresql"
    vertx:
      - groupId: "io.vertx"
        artifactId: "vertx-pg-client"
      - groupId: "io.reactiverse"
        artifactId: "reactive-pg-client"
    nodejs:
      - "pg"
    python:
      - "psycopg2"
      - "psycopg3"
      - "postgres"
redis:
  operators:
    - "redis-enterprise"
    - "redis-operator"
  dependencies:
    java:
      - groupId: "redis.clients"
        artifactId: "jedis"
      - groupId: "io.lettuce"
        artifactId: "lettuce-core"
    quarkus:
      - name: "Quarkus Redis"
        groupId: "io.quarkus"
        artifactId: "quarkus-redis-client"
    vertx:
      - name: "Vertx Reactive Redis Client"
        groupId: "io.vertx"
        artifactId: "vertx-redis-client"
    nodejs:
      - "tedis"
      - "redis"
      - "ioredis"
      - "connect-redis"
    python:
      - "redis"
      - "walrus"